(function(root){'use strict';
var CLINIC_NAME='Ahuja Dental Clinic';
function normalizeIndianMobile(raw){var input=String(raw==null?'':raw).trim();if(input==='')return{ok:false,error:'empty'};if(!/^\+?[\d\s\-().]+$/.test(input))return{ok:false,error:'invalid'};var digits=input.replace(/\D/g,'');if(digits.length===12&&digits.indexOf('91')===0)digits=digits.slice(2);else if(digits.length===13&&digits.indexOf('091')===0)digits=digits.slice(3);else if(digits.length===11&&digits.charAt(0)==='0')digits=digits.slice(1);if(!/^[6-9]\d{9}$/.test(digits)||/^(\d)\1{9}$/.test(digits))return{ok:false,error:'invalid'};return{ok:true,local:digits,number:'91'+digits}}
function buildMessage(name){var cleanName=String(name||'').replace(/\s+/g,' ').trim();var greeting=cleanName?cleanName:'Patient';return['Dear '+greeting+',','', 'Thank you for choosing '+CLINIC_NAME+' and trusting us with your dental care.','', 'We truly appreciate your visit and hope you had a comfortable experience.','', 'If you have any questions or need any assistance, please feel free to contact us.','', 'Warm regards,',CLINIC_NAME].join('\n')}
function buildWhatsAppUrl(number,message){return'https://wa.me/'+number+'?text='+encodeURIComponent(message)}
var api={normalizeIndianMobile:normalizeIndianMobile,buildMessage:buildMessage,buildWhatsAppUrl:buildWhatsAppUrl};if(typeof module!=='undefined'&&module.exports)module.exports=api;if(typeof document==='undefined')return;
var el={form:document.getElementById('form'),phone:document.getElementById('phone'),phoneField:document.getElementById('phone').closest('.field'),phoneError:document.getElementById('phone-error'),name:document.getElementById('name'),preview:document.getElementById('preview'),editor:document.getElementById('editor'),editBtn:document.getElementById('edit-btn'),resetBtn:document.getElementById('reset-btn'),copyBtn:document.getElementById('copy-btn'),clearBtn:document.getElementById('clear-btn'),status:document.getElementById('status')};
var customMessage=null,statusTimer=null;
function currentMessage(){return customMessage!==null?customMessage:buildMessage(el.name.value)}
function renderPreview(){if(customMessage===null)el.preview.textContent=buildMessage(el.name.value)}
function setStatus(text,isError,keepMs){clearTimeout(statusTimer);el.status.textContent=text;el.status.classList.toggle('bad',!!isError);if(keepMs)statusTimer=setTimeout(function(){el.status.textContent=''},keepMs)}
function showPhoneError(text){el.phoneError.textContent=text||'';el.phoneError.hidden=!text;el.phoneField.classList.toggle('invalid',!!text);el.phone.setAttribute('aria-invalid',text?'true':'false')}
function validatePhone(){var result=normalizeIndianMobile(el.phone.value);if(result.ok){showPhoneError('');return result}showPhoneError(result.error==='empty'?"Please enter the patient's mobile number.":'Please enter a valid 10-digit Indian mobile number.');el.phone.focus();return null}
function setEditing(on){if(on){el.editor.value=currentMessage();customMessage=el.editor.value}el.editor.hidden=!on;el.preview.hidden=on;el.editBtn.textContent=on?'Done Editing':'Edit Message';el.editBtn.setAttribute('aria-expanded',String(on));if(!on)el.preview.textContent=currentMessage();el.resetBtn.hidden=customMessage===null;if(on)el.editor.focus()}
function resetMessage(){customMessage=null;setEditing(false);el.preview.textContent=buildMessage(el.name.value);el.resetBtn.hidden=true}
function sendOnWhatsApp(event){event.preventDefault();var phone=validatePhone();if(!phone)return;var url=buildWhatsAppUrl(phone.number,currentMessage());setStatus('Opening WhatsApp…',false);setTimeout(function(){window.location.assign(url)},120)}
function copyMessage(){var text=currentMessage();var done=function(){setStatus('Message copied!',false,2500)};var fail=function(){setStatus('Unable to copy the message. Please select and copy it manually.',true,6000)};if(navigator.clipboard&&window.isSecureContext){navigator.clipboard.writeText(text).then(done,fail);return}var temp=document.createElement('textarea');temp.value=text;temp.setAttribute('readonly','');temp.style.position='fixed';temp.style.opacity='0';document.body.appendChild(temp);temp.select();var ok=false;try{ok=document.execCommand('copy')}catch(e){ok=false}document.body.removeChild(temp);ok?done():fail()}
function clearAll(){el.phone.value='';el.name.value='';showPhoneError('');resetMessage();setStatus('',false);el.phone.focus()}
el.name.addEventListener('input',renderPreview);el.phone.addEventListener('input',function(){if(!el.phoneError.hidden)showPhoneError('')});el.editor.addEventListener('input',function(){customMessage=el.editor.value;el.resetBtn.hidden=false});el.editBtn.addEventListener('click',function(){setEditing(el.editor.hidden)});el.resetBtn.addEventListener('click',resetMessage);el.form.addEventListener('submit',sendOnWhatsApp);el.copyBtn.addEventListener('click',copyMessage);el.clearBtn.addEventListener('click',clearAll);renderPreview()
})(typeof window!=='undefined'?window:globalThis);